.circleci/config.yml
assert/assert.go
bash/action.go
example/cmd/injection.go
example/cmd/root_test.go
fish/action.go
zsh/action.go

added injection command

---

bash/action.go
bash/snippet.go
example/cmd/root_test.go

bash: support spaces in values

---

action.go
bash/action.go
example/cmd/action.go
example/cmd/root_test.go
fish/action.go
zsh/action.go

added ActionDirectories

---

bash/snippet.go
example/cmd/root_test.go

- if last value starts with quote and xargs doesn't like it
assume it's an unmatched quote so append one to compline
- added triple backslash to space on last value so that comgen
matches it correctly (yuck)
might break some stuff but so far it seems to work
related #6

bash: added support for quoted values

---

bash/snippet.go
example/cmd/root_test.go

bash: support single quoted values

---

bash/action.go
example/cmd/root_test.go

quotation wasn't correctly filtered there so strip quotes from last word
related #6

bash fix ActionUsers and ActionGroups

---

.circleci/config.yml
bash/action.go
bash/snippet.go
example/cmd/root_test.go

bash: enabled shellcheck

---

docker-compose.yml
example/cmd/root_test.go
powershell/snippet.go

- added docker-compose to test powershell
- updated snippet to use uid.Command

powershell: use state callback

---

example/cmd/root_test.go
powershell/snippet.go

- added parameter prefix
- updated type for subcommands

powershell: ensure tooltip is not empty

---

README.md
action.go
example/cmd/root_test.go
powershell/action.go
powershell/snippet.go

- support empty completion
- only complete flags when current word starts with `--`

powershell: flag completion

---

elvish/action.go
elvish/snippet.go

needed replacer for special characters

elvish: fix flag usage

---

carapace.go
elvish/snippet.go
example/cmd/root_test.go

- fix aargument order
- add quotes

elvish: fix snippet

---

carapace.go
elvish/snippet.go
example/cmd/callback.go
example/cmd/root_test.go
zsh/snippet.go
zsh/snippet_test.go

added wildcard completion

---

carapace.go
go.mod
go.sum

traverse parent processes and if any executable matches known shell generate corresponding completion script on `_carapace` invocation

determine shell using parent process name

---

.gitignore
README.md
carapace/cmd/root.go
carapace/main.go

initial version with gnu help parser

standalone: added binary

---

Dockerfile.elvish
elvish/action.go
example/cmd/root_test.go

elvish: replaced display-suffix with display

---

.gitignore
README.md
carapace/main.go
caraparse/cmd/root.go
caraparse/main.go

fixes #55 
made a mistake in #56

renamed parser binary to caraparse

---

fish/action.go

descriptions were not sanitized
fixes #65

fish: fix ActionValuesDescribed

---

elvish/action.go
example/cmd/root_test.go

elvish: added missing quotes to ActionValuesDescribed

---

carapace.go
zsh/action.go
zsh/snippet.go

- added shell detection for empty paramater

zsh: updated replacer

---

Dockerfile.oil
carapace.go
docker-compose.yml

added oil shell (alias for bash)

---

example/cmd/root_test.go
fish/action.go
powershell/action.go

ensured descripton is not empty

---

bash/snippet.go
elvish/snippet.go
example/cmd/action.go
example/cmd/root_test.go
fish/snippet.go
powershell/snippet.go
zsh/snippet.go
zsh/snippet_test.go

support optarg flags

---

Dockerfile.xonsh
README.md
action.go
carapace.go
docker-compose.yml
example/cmd/action.go
example/cmd/root_test.go
xonsh/action.go
xonsh/snippet.go

#85 
still messy, but seems to work so far

added xonsh

---

example/cmd/root_test.go
xonsh/snippet.go

xonsh: added check if command is correct

---

example/cmd/root_test.go
xonsh/snippet.go

xonsh: better just  check with startswith

---

bash/action.go
elvish/action.go
elvish/snippet.go
example/cmd/root_test.go
fish/action.go
fish/snippet.go
powershell/action.go
powershell/snippet.go
xonsh/action.go
xonsh/snippet.go
zsh/action.go
zsh/snippet.go

- `\n` replaced
- nonlocal vars to allow callback access
- added completer description
- function name fix (`-` is not allowed)
- skip boolean flag action

xonsh: various fixes

---

action.go
bash/action.go
bash/snippet.go
carapace.go
common/value.go
example/cmd/action/os.go
example/cmd/multiparts.go
example/cmd/root_test.go
go.sum
uid/uid.go

- updated Action util functions
- added InvokedAction type

added multiparts test

---

Dockerfile.oil
action.go
xonsh/snippet.go

xonsh: fixed lazy snippet

---

example/cmd/root_test.go
fish/snippet.go
zsh/action.go
zsh/snippet.go

- zsh: use `{}` for callback to avoid flag arguments
- fish: invoke and remove autoloaded completion (https://github.com/fish-shell/fish-shell/issues/6716)

fix completion

---

.circleci/config.yml
carapace.go

- enabled when environment variable `CARAPACE_LOG` is set
- logs to {tmpdir}/carapace/{binaryname}.log

added basic logging

---

carapace.go

added powershell.exe to determineShell

---

fish/snippet.go

fish: do-complete arg as optarg

---

Dockerfile.powershell
powershell/snippet.go

powershell: fix lazy script

---

example/cmd/root_test.go
internal/bash/snippet.go

bash: fix multiparts slash

---

example/cmd/root_test.go
internal/elvish/snippet.go

- changed delimiter for join/xargs
#99

elvish: fix space in values

---

action.go
docs/src/carapace/action/actionCallback.md
docs/src/carapace/action/actionMessage.md
example/cmd/multiparts.go

- carapace.CallbackValue is updated during invocation
- updated docs

ActionMultiParts: support nesting

---

action.go

ToMultipartsA: fix prefix filtering

---

example/cmd/root_test.go
internal/powershell/action.go
internal/powershell/snippet.go

powershell: escape , in values

---

example/cmd/multiparts.go
example/cmd/root_test.go
internal/bash/action.go
internal/bash/snippet.go

bash: seperate visual from inserted value

---

action.go

ActionMultiParts: hide description for partial values

---

action.go
example/cmd/root_test.go
internal/bash/snippet.go

bash: skip prefix workaround if values == display

---

example/cmd/root_test.go
internal/bash/snippet.go

bash: empty value as dummy works as well

---

Dockerfile
action.go
carapace.go
example/_test/invoke_oil
example/main_test.go
internal/oil/action.go
internal/oil/snippet.go

oil support

---

carapace.go
example/main_test.go

fix shorthandlookup

---

example/cmd/_test/xonsh.py
internal/xonsh/action.go
internal/xonsh/snippet.go

xonsh: fix quotation

---

example/cmd/_test/xonsh.py
internal/xonsh/snippet.go

xonsh: fix begidx for quoted values

---

action.go
carapace.go
example/_test/invoke_xonsh
example/main_test.go

handle unknown flag

---

action.go
example/main_test.go

complete shorthand flag series

---

carapace.go

invoke correct action for persistent flags

---

action.go

ActionFiles: support `./` as directory

---

action.go
internal/zsh/action.go

actionPath: support `~`

---

example/cmd/_test/elvish.elv
internal/elvish/action.go
internal/elvish/snippet.go

related #3 
related #192
related #194
related #215

elvish: removed eval step

---

example/cmd/_test/powershell.ps1
internal/powershell/action.go
internal/powershell/snippet.go

related #3
related #192
related #194
related #215

powershell: removed invoke-expression

---

example/cmd/_test/xonsh.py
internal/xonsh/action.go
internal/xonsh/snippet.go

related #3
related #192
related #194
related #215

xonsh: remove eval

---

example/cmd/_test/fish.fish
internal/fish/action.go
internal/fish/snippet.go

related #3
related #192
related #194
related #215

fish: remove eval

---

example/cmd/_test/zsh.sh
internal/zsh/action.go
internal/zsh/snippet.go

related #3
related #192
related #194
related #215

zsh: removed eval

---

example/cmd/_test/elvish.elv
internal/elvish/snippet.go

elvish: removed empty parameter fix

---

internal/elvish/action.go

elvish: readd linebreak filtering

---

Dockerfile
internal/fish/action.go

fish: reenable special characters

---

Dockerfile
internal/fish/action.go

Revert "Merge pull request #238 from rsteube/fish-reenable-special-characters"

---

action.go
carapace.go
docs/src/carapace/action/actionCallback.md
docs/src/carapace/action/actionMultiParts.md
docs/src/carapace/action/custom.md
docs/src/carapace/invokedAction/filter.md
docs/src/carapace/invokedAction/merge.md
docs/src/carapace/invokedAction/prefix.md
docs/src/carapace/invokedAction/suffix.md
docs/src/carapace/invokedAction/toMultiPartsA.md
example/cmd/action/net.go
example/cmd/action/os.go
example/cmd/callback.go
example/cmd/condition.go
example/cmd/multiparts.go
internal/bash/snippet.go
internal/elvish/snippet.go
internal/fish/snippet.go
internal/oil/snippet.go
internal/powershell/snippet.go
internal/xonsh/snippet.go
internal/zsh/snippet.go

context struct

---

Dockerfile
action.go
carapace.go
internal/common/value.go
internal/nushell/action.go

nushell poc

---

internal/fish/action.go
internal/fish/snippet.go

fish: re-enabled special characters

---

docs/src/SUMMARY.md
docs/src/carapace/action/actionCallback.md
docs/src/carapace/action/actionMultiParts.md
docs/src/carapace/gen/flagCompletion.md
docs/src/carapace/gen/hiddenSubcommand.md
docs/src/lazycomplete.md

updated docs

---

action.go

wrapped static actions in ActionCallback

---

example/_test/invoke_xonsh

xonsh: prevent banner in invokation script

---

Dockerfile

oil: fix completion in container

---

example/cmd/_test/xonsh.py
internal/xonsh/action.go
internal/xonsh/snippet.go

xonsh: use raw strings

---

example/cmd/_test/powershell.ps1
internal/common/value.go
internal/powershell/action.go
internal/powershell/snippet.go

powershell reenable special characters

---

internal/oil/action.go

oil: re-enabled special characters

---

docker-compose.yml

- default currently has drawing issues when content exceeds terminal
width: https://github.com/oilshell/oil/issues/795

oil: use completion-display minimal

---

carapace.go
docs/src/carapace/gen.md
example/cmd/root.go
example/main_test.go
storage.go

use references for internal action map

---

Dockerfile

nushell: use poc in container

---

example/cmd/_test/zsh.sh
internal/zsh/action.go
internal/zsh/snippet.go

zsh re-enabled special characters

---

Dockerfile
internal/bash/action.go

bash: re-enabled special characters

---

action.go
example/cmd/_test/elvish.elv
example/cmd/_test/zsh.sh
internal/bash/action.go
internal/elvish/action.go
internal/elvish/snippet.go
internal/fish/action.go
internal/ion/action.go
internal/nushell/action.go
internal/oil/action.go
internal/powershell/action.go
internal/xonsh/action.go
internal/zsh/action.go
internal/zsh/snippet.go

implicit nospace

---

carapace.go

FlagCompletion: support multiple calls

---

internal/common/traverse.go

fix traverse for fully matching subcommand currently being completed

---

carapace.go
carapace_test.go

fix context

---

carapace.go
internal/bash/action.go
internal/elvish/action.go
internal/fish/action.go
internal/ion/action.go
internal/nushell/action.go
internal/oil/action.go
internal/powershell/action.go
internal/xonsh/action.go
internal/zsh/action.go

fixed partial optarg value not completed

---

action.go
carapace.go
override.go

long shorthand support

---

batch.go
batch_test.go
docs/src/SUMMARY.md
docs/src/carapace/batch.md
docs/src/development/anatomyOfAShellCLI.md
example/cmd/batch.go

add `Batch` function

---

carapace.go
internal/common/traverse.go
internal/common/traverse_test.go

support `cmd.DisableFlagParsing`

---

internal/tcsh/action.go
internal/tcsh/snippet.go

tcsh: prevent default space suffix

---

.circleci/config.yml
Dockerfile

build docker image on circleci

---

example/cmd/_test/powershell.ps1
internal/powershell/snippet.go

powershell: truncate args to cursor position

---

example/cmd/_test/powershell.ps1
internal/powershell/snippet.go

powershell: unescape comma

---

internal/tcsh/action.go

tcsh: remove curly braces

---

action.go
action_test.go
batch_test.go
invokedAction.go

InvokedAction: use composition

---

example/_test/invoke_xonsh
example/cmd/_test/xonsh.py
example/main_test.go
internal/xonsh/snippet.go

xonsh: use completion context

---

example/cmd/_test/xonsh.py
internal/xonsh/snippet.go

xonsh: prevent file completion fallback

---

example/cmd/_test/xonsh.py
internal/xonsh/snippet.go

xonsh: remove quotes from prefix

---

example/cmd/_test/elvish.elv
internal/elvish/snippet.go

related: https://github.com/rsteube/carapace-bin/pull/798

elvish: fix deprecation notices from 0.17

---

carapace.go
internal/export/snippet.go

exports command structure as json

added export

---

internal/export/snippet.go

Added code to export Url, note I haven't verified that it is working as I'm somewhat new to go.

Added url to export

---

action_test.go

test: filter vendor folder

---

action_test.go

test: filter example binary

---

carapace.go
internal/bash_ble/action.go
internal/bash_ble/snippet.go
invokedAction.go
pkg/ps/ps.go

https://github.com/akinomyoga/ble.sh
#431

support ble.sh

---

example/cmd/_test/bash-ble.sh
example/cmd/root_test.go
internal/bash_ble/snippet.go

bash-ble: fallback to bash if not attached

---

example/cmd/_test/bash-ble.sh
internal/bash_ble/snippet.go

bash-ble: prevent default

---

action.go
carapace_test.go
defaultActions.go
defaultActions_test.go

context: added env

---

pkg/ps/ps.go

bash-ble: add auto-detect

---

carapace_test.go
example/_test/invoke_elvish
example/cmd/_test/elvish.elv
internal/elvish/action.go
internal/elvish/snippet.go

fix #51
needs https://github.com/elves/elvish/commit/84b72af4ca3ff56233271807237126f4fbb3478c (0.18.0)
build needs elvish 0.18.0 to pass

elvish: colored descriptions

---

action.go
action_test.go
carapace_test.go
defaultActions.go
defaultActions_test.go
example/_test/invoke_elvish
example/_test/invoke_xonsh
example/cmd/_test/elvish.elv
example/cmd/action.go
internal/assert/assert.go
internal/common/value.go
internal/elvish/action.go
internal/elvish/snippet.go
invokedAction.go
pkg/style/style.go

added support for colored display values

---

example/cmd/_test/zsh.sh
internal/shell/zsh/action.go
internal/shell/zsh/snippet.go
pkg/style/style.go

zsh tabular color

---

internal/shell/zsh/action.go

zsh: disable colors for large amount of values

---

action.go
action_test.go
carapace.go
carapace_test.go
defaultActions.go
example/cmd/_test/elvish.elv
example/cmd/action.go
internal/config/config.go
internal/shell/elvish/action.go
internal/shell/elvish/snippet.go
internal/shell/zsh/action.go
invokedAction.go
pkg/style/config.go
pkg/style/keyword.go
pkg/style/path.go
pkg/style/style.go
third_party/github.com/elves/elvish/pkg/cli/lscolors/lscolors.go

color config

---

example/main_test.go

powershell: disable test

---

internal/shell/nushell/action.go

needs https://github.com/nushell/nushell/pull/5298

nushell: descriptions

---

example/cmd/action/os/os.go
example/cmd/root_test.go
internal/assert/assert.go
internal/cache/cache.go
pkg/cache/cache.go
third_party/github.com/mitchellh/go-ps/process_linux.go
third_party/golang.org/x/sys/execabs/execabs_test.go

replace deprecated ioutil

---

Dockerfile

This reverts commit ec1e801749732d77ddbccb99e2243c128db8124d, reversing
changes made to 66c60950e20330ff1841a1581ef379fc0b65e5ef.

Revert "Merge pull request #513 from rsteube/fix-ci"

---

invokedAction.go

ActionMultiParts: support multiple dividers

---

action_test.go
invokedAction.go
invokedAction_test.go

ToMultiParts: fix display

---

carapace.go

- use github actions
- coveralls
- test: inline interface

test inline interface

---

README.md
docs/src/carapace/gen/hiddenSubcommand.md
example/cmd/_test/nushell.nu
internal/shell/nushell/snippet.go

nushell: update snippet

---

example/cmd/_test/zsh.sh
internal/shell/zsh/action.go
internal/shell/zsh/snippet.go

fix #313
fix https://github.com/rsteube/carapace-bin/issues/1277

zsh: fix tilde expansion

---

context.go
example/cmd/_test/zsh.sh
internal/shell/zsh/snippet.go

zsh: support static named directories in file completion

---

context.go
context_test.go
example/cmd/_test/zsh.sh
internal/shell/zsh/action.go
internal/shell/zsh/namedDirectory.go
internal/shell/zsh/snippet.go

related #313
related rsteube/carapace-bin#1277

zsh: fix named directories

---

invokedAction.go
invokedAction_test.go

ToMultiParts: fix bracket completion (incomplete quickfix)

---

carapace.go

added PreRun

---

carapace.go
carapace_test.go
example/cmd/action.go
example/main_test.go

fix positional completion for word ending with space

---

storage.go

storage: check persistent flags

---

storage.go

This reverts commit 2dc9ccbc0473d19d2ab7acc401c36992a87a5336, reversing
changes made to f78111d8a2d354a21304ebe22edab12217a23c03.

Revert "Merge pull request #573 from rsteube/storage-check-persistent-flags"

---

carapace.go
carapace_test.go
command.go
log.go

moved logger to separate file

---

defaultActions.go

actionFlags: hardcoded multipart completion for evaluation

---

action.go
action_test.go
batch_test.go
compat.go
defaultActions.go
defaultActions_test.go
internal/common/suffix.go
internal/shell/bash/action.go
internal/shell/bash_ble/action.go
internal/shell/elvish/action.go
internal/shell/export/action.go
internal/shell/fish/action.go
internal/shell/ion/action.go
internal/shell/nushell/action.go
internal/shell/oil/action.go
internal/shell/powershell/action.go
internal/shell/shell.go
internal/shell/tcsh/action.go
internal/shell/xonsh/action.go
internal/shell/zsh/action.go
invokedAction.go

conditional nospace

---

action.go
example/cmd/action.go

added Action.UniqueList

---

example/cmd/_test/powershell.ps1
internal/shell/powershell/snippet.go

powershell: fix 7.3.0

---

example/cmd/action.go
example/cmd/batch.go
example/cmd/callback.go
example/cmd/condition.go
example/cmd/root.go
internalActions.go

actionCommands: use Command.GroupID for tags

---

internalActions.go

actionSubcommands: implicit group name

---

docs/src/SUMMARY.md
docs/src/carapace/action/style.md
docs/src/carapace/action/tag.md

doc: added Action.Tag

---

docs/src/SUMMARY.md
docs/src/carapace/action/usage.md

doc: added usage

---

example/cmd/_test/zsh.sh
internal/shell/zsh/action.go
internal/shell/zsh/snippet.go

zsh: usage support

---

example/cmd/_test/zsh.sh
example/cmd/action.go
internal/shell/zsh/action.go
internal/shell/zsh/message.go
internal/shell/zsh/snippet.go
internal/shell/zsh/zstyle.go

zsh: arrange values using _describe

---

internal/shell/zsh/zstyle.go

zsh: fix style for values without description

---

example/cmd/_test/zsh.sh
internal/shell/zsh/action.go
internal/shell/zsh/snippet.go

zsh: fix escaping

---

example/cmd/_test/zsh.sh
internal/shell/zsh/snippet.go

zsh: fix zstyle curcontext

---

action.go
action_test.go
compat.go
defaultActions.go
internal/common/suffix.go
internal/common/suffix_test.go
internal/shell/bash/action.go
internalActions.go
invokedAction.go

action: removed internal util functions

---

example/cmd/_test/zsh.sh
internal/common/value.go
internal/shell/zsh/action.go
internal/shell/zsh/message.go
internal/shell/zsh/snippet.go
internal/shell/zsh/zstyle.go
internalActions.go

zsh: tag support

---

example/cmd/flag.go
example/cmd/special.go
example/main_test.go

example: added flags

---

action.go
context.go
defaultActions.go
internalActions.go
pkg/style/path.go
third_party/github.com/elves/elvish/pkg/cli/lscolors/lscolors.go

style: fix context awareness

---

example/cmd/root_test.go
internalActions.go

actionFlags: multipart completion for flags as default

---

action.go
example/cmd/modifier.go
example/cmd/modifier_test.go

action: added Timeout

---

traverse.go

traverse: fix _carapace completion

---

carapace.go
example-nonposix/cmd/root_test.go
example/cmd/action_test.go
example/cmd/modifier_test.go
example/cmd/multiparts_test.go
example/cmd/root_test.go
pkg/sandbox/sandbox.go
pkg/sandbox/sandbox_test.go
storage.go
traverse.go

sandbox: added Command

---

example/cmd/action_test.go
traverse.go

traverse: fix dash flag completion

---

example/cmd/action.go
example/cmd/action_test.go
traverse.go

fix dash completion

---

example-nonposix/cmd/root.go
internal/pflagfork/flag.go
internalActions.go
traverse.go

- parts only consists of args related to current occurrence

nargs: keep repeatable behaviour

---

internal/cache/cache.go
internal/config/config.go
pkg/xdg/xdg.go

support xdg base directories

---

.dockerfile/root/.bashrc
.dockerfile/root/.config/elvish/rc.elv
.dockerfile/root/.config/fish/config.fish
.dockerfile/root/.config/ion/initrc
.dockerfile/root/.config/nushell/config.nu
.dockerfile/root/.config/nushell/env.nu
.dockerfile/root/.config/nushell/starship.nu
.dockerfile/root/.config/oil/oshrc
.dockerfile/root/.config/powershell/Microsoft.PowerShell_profile.ps1
.dockerfile/root/.config/starship.toml
.dockerfile/root/.config/xonsh/rc.xsh
.dockerfile/root/.tcshrc
.dockerfile/root/.zshrc
.dockerfile/usr/local/bin/entrypoint.sh
.dockerfile/usr/local/bin/target.sh
.dockerignore
Dockerfile
docker-compose.yml

- docker: update versions
- tmp

docker update versions

---

example/cmd/_test/nushell.nu
internal/shell/nushell/snippet.go

related rsteube/carapace-bin#1516

nushell: setup changes since nushell 0.72

---

action.go

checksum needs to be regenerated after invocation

cache: fix cache checksum

---

example/cmd/root_test.go
traverse.go

- gh-pages: fix path
- flags: support optarg completion for bool flags as well

flag bool optarg

---

action_test.go
carapace_test.go
command.go
compat.go
context.go
defaultActions.go
defaultActions_test.go
docs/src/carapace/action/custom.md
docs/src/carapace/defaultActions/actionCallback.md
docs/src/carapace/defaultActions/actionMultiParts.md
internalActions.go
invokedAction.go
invokedAction_test.go
pkg/sandbox/sandbox.go
traverse.go

- tmp
- Context: renamed CallbackValue to Value

context rename callbackvalue

---

context.go
internal/common/value.go
internal/config/env.go
internal/env/env.go
internal/shell/shell.go
internal/shell/zsh/namedDirectory.go
log.go
traverse.go

support NO_COLOR env

---

carapace_test.go
defaultActions.go
pkg/style/config.go
pkg/style/style.go

style: removed `gray`

---

example/cmd/interspersed.go
example/cmd/interspersed_test.go
example/cmd/root_test.go
internal/pflagfork/flagset.go
traverse.go

related https://github.com/rsteube/carapace-bin/pull/1720

support FlagSet.interspersed

---

carapace.go
compat.go
storage.go

storage: added mutexes

---

Dockerfile

docker: added gocovmerge

---

.github/workflows/go.yml
.gitignore
internal/env/env.go
pkg/sandbox/sandbox.go

sandbox: enable coverage

---

example/cmd/root_test.go
traverse.go

traverse: fix partial optarg completion

---

internal/cache/cache.go

cache: allow zero timeout duration

---

internal/shell/bash/action.go
internal/shell/bash/patch.go

bash: fix wordbreaks

---

internal/common/value.go
internal/env/env.go
invokedAction.go
pkg/match/match.go

elvish: https://elv.sh/ref/edit.html#matcher
```elvish
set edit:completion:matcher[argument] = {|seed| edit:match-prefix $seed &ignore-case=$true }
```
fix #757

added Match

---

example/cmd/modifier_test.go

ChdirF: added test

---

action.go
defaultActions.go
pkg/match/match.go

- fixed `Action.Prefix`
- fixed `actiondirectories`

Match: added `TrimPrefix`

---

example/cmd/_test/nushell.nu
internal/shell/nushell/snippet.go

nushell: fix snippet

---

.dockerfile/root/.config/nushell/config.nu
.dockerfile/root/.config/nushell/env.nu
.dockerfile/root/.config/nushell/starship.nu
Dockerfile

docker: updated version

---

complete.go
example/cmd/_test/bash-ble.sh
example/cmd/_test/bash.sh
internal/shell/bash/patch.go
internal/shell/bash/snippet.go

bash: fix compline patching

---

experimental.go
pkg/x/x.go

added experimental functions

---

defaultActions.go
example/cmd/flag_disabled.go
example/cmd/flag_disabled_test.go

FlagParsingDisabled: fix positional completion

---

action.go
action_test.go
compat.go
invokedAction.go
storage.go

InvokedAction: private composition

---

example/cmd/_test/nushell.nu
internal/shell/nushell/snippet.go

related rsteube/carapace-bin#2166

nushell: spread operator

---

example/cmd/_test/xonsh.py
internal/shell/xonsh/snippet.go

related carapace-sh/carapace-bin#2414

xonsh: fix script

---

internal/pflagfork/flagset_test.go
pkg/ps/ps.go
traverse.go

fix https://github.com/carapace-sh/carapace-bin/pull/2477

ps: update ble detection

---

context.go
context_test.go

related carapace-sh/carapace-bin#2480

context: abs - fix `~`

---

example/cmd/action_test.go
internalActions.go

related carapace-sh/carapace-bin#2359

actionPath: fix symlinks

---

example/cmd/_test/powershell.ps1
internal/shell/powershell/snippet.go

related carapace-sh/carapace-bin#2565

powershell: support exe extension

---

internal/env/env.go
internal/shell/shell.go

env: added `CARAPACE_NOSPACE`

---

pkg/traverse/golang.go

traverse: fix GoBinDir

---

internal/shell/elvish/snippet.go

related carapace-sh/carapace-bin#2565

elvish: register `.exe` completion on windows

---

example/cmd/_test/zsh.sh
internal/shell/zsh/snippet.go

zsh: slice words to current

---

pkg/match/match.go

match: fix equal

---

example/cmd/_test/zsh.sh
internal/shell/zsh/snippet.go

fix https://github.com/carapace-sh/carapace/issues/1070

zsh: slice before changing IFS

---

example/cmd/root_test.go
internal/env/env.go
internal/shell/shell.go
internal/shell/zsh/action.go

env: added `CARAPACE_MERGEFLAGS`

---

action_test.go
carapace_test.go

use TestMain
