bash/action.go
bash/snippet.go
example/cmd/root_test.go

- directiories have trailing '/'
- no space when completing directories

bash: fix ActionFiles

---

example/cmd/root_test.go
fish/snippet.go

- commandline can tokenize with '-t' but that removes quotes so
simply check xargs for error to decide which quote to add
related #6

fish: support quoted values

---

bash/snippet.go
example/cmd/root_test.go

repeated substitution needs a double slash
related #6

bash: fix parameter expansion

---

bash/snippet.go
carapace.go
elvish/snippet.go
example/cmd/root_test.go
fish/snippet.go
powershell/snippet.go
uid/uid.go
zsh/action.go
zsh/snippet.go
zsh/snippet_test.go

completions for root cmd name and callbacks are directed to the carapace
binary

initial standalone support

---

Dockerfile.elvish
README.md
action.go
bash/action.go
bash/snippet.go
carapace.go
elvish/action.go
example/cmd/action.go
example/cmd/callback.go
example/cmd/root_test.go
fish/action.go
fish/snippet.go
go.mod
go.sum
powershell/action.go
powershell/snippet.go
uid/uid.go
zsh/action.go

ActionMultiParts is now a callback action and works for all shells
- updated elvish to HEAD version (docker)
- added NestedValue for callback actions returned during callback
(callback function must be executed for actual values)
- added callback for ActionUsers, ActionGroups and ActionHosts (to
support all shells - currently only for linux)
- added ActionPrefixValues (WIP: needed for ActionMultiParts)
- added carapace.CallbackValue whose content is set to currently completed
argument during callback
- replaced '-' with "''" as position indicator during callback (scripts)
- bash compopt nospace now set for `/=@:.,` suffixes (same as in latest
fish version)
- updated traverse for position indicator change
- added missing quotation for fish

updated ActionMultiParts

---

powershell/action.go

descriptions were not sanitized
fixes #67

powershell: fixed ActionValuesDescribed

---

powershell/action.go

powershell: fix `’` (breaks completion)

---

example/cmd/root_test.go
internal/bash/snippet.go

fixes #164 
Although multiple values are provided bash might insert part of it if the all have the same prefix.
But this would skip/remove the prefix of an ActionMultiParts as this are the display values and not what is intended to be inserted into the line.
To prevent this a dummy value (`_`) is added.

bash: fix prefix removal

---

action.go

only show when CallbackValue has an explicit `.` prefix
fix #213

actionPath: filter hidden files/folders

---

action.go

ActionMultiParts: fix context for empty divider

---

example/cmd/_test/zsh.sh
internal/zsh/action.go
internal/zsh/snippet.go

Mimic standard completion style by only showing one per line with an alligned `--` delimiter
related #rsteube/carapace-bin#417

zsh: mimic standard completion style

---

internal/tcsh/action.go

seems tcsh filters display values that don't match current prefix so use
the actual value (which results in long display strings)
#331

tcsh: fix display values not shown

---

compat.go

caused by `cobra.ShellCompDirectiveError`

compat: prevent file completion fallback

---

internal/common/traverse.go

```sh
carapace --style carapace<TAB>
```
Caused an error because the commands name fully matched but was the root
command (parentCmd == nil).

fix traverse

---

example/cmd/action_test.go
internal/common/traverse.go
internal/config/env.go
pkg/sandbox/sandbox.go

traverse: allow unknown flags when CARAPACE_LENIENT is set

---

example/cmd/modifier.go
example/cmd/modifier_test.go
invokedAction.go
invokedAction_test.go

ToMultiParts: fix divider with more than one character

---

internal/shell/zsh/zstyle.go

zstyle pattern for `matching` was matching `matching name` as well,
because `*` would match anything.
```
matching name  -- should be red
matching       -- should be blue
```
Using `[ ]##` now (one or more space).

zsh: fix zstyle matching

---

pkg/xdg/xdg.go

related rsteube/carapace-bin#1692

xdg: always use slash as delimiter

---

traverse.go

- fix `go tool cover -f<TAB>` => `error: unknown shorthand flag: -f`

traverse: fix shorthand flagseries check

---

defaultActions_test.go
example/cmd/chain.go
example/cmd/chain_test.go
example/cmd/root_test.go
internal/pflagfork/flag.go
internal/pflagfork/flagset.go
internal/pflagfork/flagset_test.go
internalActions.go
traverse.go

fix https://github.com/rsteube/carapace/issues/733
fix https://github.com/rsteube/carapace/issues/504

traverse: fix shorthand chain

---

complete.go
example/cmd/_test/bash-ble.sh
example/cmd/_test/bash.sh
go.work.sum
internal/shell/bash/patch.go
internal/shell/bash/snippet.go

bash: split COMP_LINE with shlex

---

.github/workflows/go.yml
carapace.go
storage.go
storage_test.go

storage: fix concurrent map read/write

---

carapace.go
command.go

standalone: prevent local `_carapace` completion

---

invokedAction.go

This can still be problematic when multiple values have the same prefix,
but a different tag.
Should work for most cases though.

ToMultiParts: keep tag for previous segments

---

example/cmd/_test/bash-ble.sh
example/cmd/_test/bash.sh
internal/shell/bash/action.go
internal/shell/bash/patch.go
internal/shell/bash/snippet.go

bash: handle COMP_TYPE

---

example/cmd/_test/powershell.ps1
internal/shell/powershell/snippet.go

related carapace-sh/carapace-bin#2565

powershell: register with list

---

pkg/xdg/xdg.go

xdg: ignore relative paths

---

docs/src/development/vhs/doubleQuoteOpen/out/doubleQuoteOpen.zsh.ascii
docs/src/development/vhs/singleQuoteOpen/out/singleQuoteOpen.zsh.ascii
example/cmd/_test/zsh.sh
internal/env/env.go
internal/shell/zsh/action.go
internal/shell/zsh/snippet.go

zsh: fix quoting state

---

command.go
complete.go
example/cmd/_test/cmd-clink.lua
example/cmd/root_test.go
go.mod
internal/shell/cmd_clink/action.go
internal/shell/cmd_clink/patch.go
internal/shell/cmd_clink/snippet.go
internal/shell/shell.go
pkg/ps/ps.go

shell: cmd-clink

---

complete.go
internal/shell/bash/action.go

bash: fix path containing space with `~` prefix

---

action.go
defaultActions.go
docs/book.toml
example/cmd/_test_files/files_linux.go
example/cmd/_test_files/go.mod
pkg/uid/path.go
pkg/uid/uid.go

uid: escape paths

---

defaultActions.go
example/cmd/subcommand_test.go
internal/env/env.go
internalActions.go

fix carapace-sh/carapace-bin#2852

env: hidden - extend config to skip `_carapace` command

---

internal/common/value.go
internal/shell/shell.go

e.g. `adb pull DEVICE_FILE {DEVICE_FILE | LOCAL_FILE}...`

value: support duplicates
